stages:          # List of stages for jobs, and their order of execution
  # - build
  - test
  # - deploy

flyway-test-job:
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: achievements_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: franny_devs
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_URL: jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
  image: postgres
  stage: test
  before_script:
    - apt-get update -y && apt-get install -y wget
    - wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/11.3.0/flyway-commandline-11.3.0-linux-x64.tar.gz | tar -xvz && ln -s `pwd`/flyway-11.3.0/flyway /usr/local/bin
  script:
    - flyway -url=$POSTGRES_URL -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD migrate
# unit-test-job:   # This job runs in the test stage.
#   stage: test    # It only starts when the job in the build stage completes successfully.
#   script:
#     - echo "Running unit tests... This will take about 60 seconds."
#     - sleep 60
#     - echo "Code coverage is 90%"

# lint-test-job:   # This job also runs in the test stage.
#   stage: test    # It can run at the same time as unit-test-job (in parallel).
#   script:
#     - echo "Linting code... This will take about 10 seconds."
#     - sleep 10
#     - echo "No lint issues found."

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
