#Fetch minified node imag on apline linux
FROM node:slim

#Declaring env
ENV NODE_ENV=development

#Setting up the work directory
WORKDIR /express-docker

# Copy all the files in our project
COPY . .

# Installig dependencies
RUN npm install

# Starting our application
CMD ["node", "index.js"]

# Exposing server port
EXPOSE 5007