openapi: 3.0.0

info:
  title: Franciscan Achievement Tracker
  description: no you
  version: 1.0.0
  contact:
    name: Evan Whitmer
    email: ewhitmer001@student.franciscan.edu

servers:
  - url: http://localhost:5007
    description: The current url as the backend is still only for local serving

paths:
  /api/achievements:
    get:
      summary: Get a list of achievements
      description: Get a list of achievements from the API.
      responses:
        '200':
          description: Successful response
          content:
            application/javascript:
              example:
                achievements:
                  - id: 1
                    title: The Source and The Summit
                    category: Franny Basics
                    description: Attend Mass on Campus
                    prerequisite: null
                    points: 10
                  - id: 2
                    title: Cafarrhea
                    category: Franny Basics
                    description: Eat at the Caf
                    prerequisite: null
                    points: 20
                  - id: 3
                    title: Lets Shake Things Up
                    category: Franny Basics
                    description: Eat at the Pub
                    prerequisite: null
                    points: 20
  /api/achievements/{id}:
    get:
      summary: Get achievements by ID
      description: Get a single user from the API.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                  - id: 1
                    title: The Source and The Summit
                    category: Franny Basics
                    description: Attend Mass on Campus
                    prerequisite: null
                    points: 10
        '404':
          description: Achievement not found