openapi: 3.0.0

info:
  title: Franciscan Achievement Tracker
  description: App where Franciscan students can track achievements earned in their time at Franciscan. Achievemnts range from simple to silly & elaborate.
  version: 1.0.0
  contact:
    name: Evan Whitmer
    email: ewhitmer001@student.franciscan.edu

servers:
  - url: http://localhost:5007
    description: The current url as the backend is still only for local serving

paths:
  /api/achievements:
    get:
      summary: Get a list of achievements
      description: Get a list of achievements from the API.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/achievements'
              example:
                achievements:
                  - id: 1
                    title: Cafarrhea
                    category: Franny Basics
                    description: Eat at the Caf
                    prerequisite: null
                    points: 10
                  - id: 2
                    title: The Grand Slam
                    category: Spiritual
                    description: Attend all four daily masses in one day
                    prerequisite: null
                    points: 100
                  - id: 3
                    title: Four Years of B.S.
                    category: Academic
                    description: Be a STEM major
                    prerequisite: null
                    points: 20
  /api/achievements/{id}:
    get:
      summary: Get achievements by ID
      description: Get a single achievements from the API.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/achievements'
              example:
                - id: 1
                  title: Cafarrhea
                  category: Franny Basics
                  description: Eat at the Caf
                  prerequisite: null
                  points: 10
        '404':
          description: Achievement not found

components:
  schemas:
    achievements:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        category:
          type: string
        description:
          type: string
        prerequisite:
          type: string
        points:
          type: integer
          format: int64
